server {
    listen 8091;
    location / { root /usr/share/nginx/html/owl-solution; index index.html; }
}

server {
    listen 8092;
    location / { root /usr/share/nginx/html/dynamic-ui-bridge; index index.html; }
}

server {
    listen 8093;
    location / { root /usr/share/nginx/html/real-time-speech-translator; index index.html; }
}

server {
    listen 8094;
    location / { root /usr/share/nginx/html/vlasiuk-me; index index.html; }
}

server {
    listen 8095;
    location / {
        root /usr/share/nginx/html/tsb-enterprise;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 8096;
    port_in_redirect off;
    location / {
        root /usr/share/nginx/html/olena-vlasiuk-me;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}