server {
    listen 8091;
    location / { root /usr/share/nginx/html/owl-solution; index index.html; }
}

server {
    listen 8092;
    location / { root /usr/share/nginx/html/dynamic-ui-bridge; index index.html; }
}

server {
    listen 8093;
    location / { root /usr/share/nginx/html/real-time-speech-translator; index index.html; }
}

server {
    listen 8094;
    location / { root /usr/share/nginx/html/vlasiuk-me; index index.html; }
}

server {
    listen 8095;
    location / {
        proxy_pass http://astro-tsb-dev:4321;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 8096;
    location / {
        proxy_pass http://astro-olena-vlasiuk-dev:4322;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 8097;
    location / {
        proxy_pass http://astro-olena-vlasiuk-dev:4323;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}