version: '3.3'

services:
  dev-server:
    build:
      context: .
      target: dev
    container_name: astro-dev
    environment:
      - SITE_NAME=${SITE_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: npm run dev

  nginx-prod:
    build:
      context: .
      target: prod
    container_name: astro-prod
    ports:
      - "8091-8097:8091-8097"