version: '3.3'

services:
  dev-server:
    image: astro-dev:local
    container_name: astro-dev
    environment:
      - SITE_NAME=${SITE_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: npm run dev

  nginx-prod:
    image: astro-prod:local
    container_name: astro-prod
    ports:
      - "8091-8098:8091-8098"