server {
    listen 8091;
    root /usr/share/nginx/html/owl-solution;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8092;
    root /usr/share/nginx/html/dynamic-ui-bridge;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8093;
    root /usr/share/nginx/html/real-time-speech-translator;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8094;
    root /usr/share/nginx/html/vlasiuk-me;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8095;
    root /usr/share/nginx/html/tsb-enterprise;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8096;
    root /usr/share/nginx/html/olena-vlasiuk-me;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8097;
    root /usr/share/nginx/html/auto-body-shop;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}

server {
    listen 8098;
    root /usr/share/nginx/html/uptarget-co;

    include /etc/nginx/conf.d/common_settings.inc;
    include /etc/nginx/conf.d/site_template.inc;
}